name: loving_kindness_meditation
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  quiver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: BebasNeue
      fonts: 
        - asset: fonts/BebasNeue-Regular.ttf
  
flutter_icons:
  image_path_android: assets/images/icon.png
  image_path_ios: assets/images/icon.png
  android: true
  ios: true